pbr: update to 1.2.1-r41
Remove many obsolete files.

Makefile:
* remove netifd-flavour related code
* remove trailing white spaces

Init-script:
* proper deletion of default network rules for IPv{4,6}
* fix netifd function error when IPv6 is enabled
* remove trailing white spaces

Signed-off-by: Stan Grishin <stangri@melmac.ca>
(cherry picked from commit 89e29f7141b8cbca8f40b047063f7c42d21bf391)
Signed-off-by: Stan Grishin <stangri@melmac.ca>

diff --git a/net/pbr/files/etc/init.d/pbr b/net/pbr/files/etc/init.d/pbr
--- a/net/pbr/files/etc/init.d/pbr
+++ b/net/pbr/files/etc/init.d/pbr
@@ -202,7 +202,7 @@ pbr_get_gateway4() {
 }
 pbr_get_gateway6() {
 	local iface="$2" dev="$3" gw
-	[ "$iface" = "$uplink_interface" ] && iface="$uplink_interface6"  
+	[ "$iface" = "$uplink_interface" ] && iface="$uplink_interface6"
 	network_get_gateway6 gw "$iface" true
 	if [ -z "$gw" ] || [ "$gw" = '::/0' ] || [ "$gw" = '::0/0' ] || [ "$gw" = '::' ]; then
 		gw="$(ip -6 a list dev "$dev" 2>/dev/null | grep inet6 | grep 'scope global' | awk '{print $2}')"
@@ -722,7 +722,7 @@ nft_file() {
 		;;
 		create)
 			rm -f "$nftTempFile" "$nftPermFile"
-			for i in "$nftTempFile" "$nftPermFile"; do 
+			for i in "$nftTempFile" "$nftPermFile"; do
 				mkdir -p "${i%/*}"
 			done
 			{ echo '#!/usr/sbin/nft -f'; echo ''; } > "$nftTempFile"
@@ -747,6 +747,39 @@ nft_file() {
 				output_failn
 			fi
 		;;
+		netifd_exists)
+			[ -s "$nftNetifdPermFile" ] && return 0 || return 1
+		;;
+		netifd_create)
+			rm -f "$nftTempFile" "$nftNetifdPermFile"
+			for i in "$nftTempFile" "$nftNetifdPermFile"; do
+				mkdir -p "${i%/*}"
+			done
+			{ echo '#!/usr/sbin/nft -f'; echo ''; } > "$nftTempFile"
+		;;
+		netifd_delete|netifd_rm)
+			rm -f "$nftNetifdPermFile"
+		;;
+		netifd_install)
+			[ -s "$nftTempFile" ] || return 1
+			output "Installing fw4 netifd nft file "
+			if nft_call -c -f "$nftTempFile" && \
+				cp -f "$nftTempFile" "$nftNetifdPermFile"; then
+				output_okbn
+			else
+				json add error 'errorNetifdNftFileInstall' "$nftTempFile"
+				output_failn
+			fi
+		;;
+		netifd_remove)
+			output "Removing fw4 netifd nft file "
+			if rm -f "$nftNetifdPermFile"; then
+				output_okbn
+			else
+				json add error 'errorNetifdNftFileRemove' "$nftTempFile"
+				output_failn
+			fi
+		;;
 	esac
 }
 nft() { [ -n "$*" ] && nft_file 'add_command' "$@"; }
@@ -759,7 +792,7 @@ nftset() {
 	nftset4="${nftPrefix}${iface:+_$iface}_4${target:+_$target}${type:+_$type}${uid:+_$uid}"
 	nftset6="${nftPrefix}${iface:+_$iface}_6${target:+_$target}${type:+_$type}${uid:+_$uid}"
 
-	if [ "${#nftset4}" -gt '255' ]; then 
+	if [ "${#nftset4}" -gt '255' ]; then
 		json add error 'errorNftsetNameTooLong' "$nftset4"
 		return 1
 	fi
@@ -873,7 +906,7 @@ nftset() {
 	fi
 }
 
-cleanup_rt_tables() { 
+cleanup_rt_tables() {
 	local i
 # shellcheck disable=SC2013
 	for i in $(grep -oh "${ipTablePrefix}_.*" "$rtTablesFile"); do
@@ -1071,7 +1104,7 @@ resolver() {
 				;;
 				compare_hash)
 					[ -z "$resolverSetSupported" ] && return 1
-					uci_changes 'dhcp' && uci_commit 'dhcp' 
+					uci_changes 'dhcp' && uci_commit 'dhcp'
 					local resolverNewHash
 					if [ -s "$packageDnsmasqFile" ]; then
 						resolverNewHash="$(md5sum "$packageDnsmasqFile" | awk '{ print $1; }')"
@@ -1099,6 +1132,160 @@ resolver() {
 	esac
 }
 
+netifd() {
+	# Usage: netifd install [iface] | netifd remove [iface] | netifd uninstall
+	_netifd_process_interface() {
+		local iface="$1" action="${2:-install}"
+		local rt_name="${ipTablePrefix}_${iface%6}"
+
+		uci_remove 'network' 'rule' "${rt_name}_ipv4"  2>/dev/null
+		uci_remove 'network' 'rule6' "${rt_name}_ipv6" 2>/dev/null
+
+		if [ -n "$netifd_strict_enforcement" ] && str_contains "$netifd_interface_local" "$iface"; then
+			if [ -n "$netifd_interface_default" ]; then
+				uci_add 'network' 'rule' "${rt_name}_ipv4"
+				uci_set 'network' "${rt_name}_ipv4" 'in' "${iface}"
+				uci_set 'network' "${rt_name}_ipv4" 'lookup' "${ipTablePrefix}_${netifd_interface_default}"
+				uci_set 'network' "${rt_name}_ipv4" 'priority' "${lan_priority}"
+			fi
+			if [ -n "$ipv6_enabled" ] && [ -n "$netifd_interface_default6" ]; then
+				uci_add 'network' 'rule6' "${rt_name}_ipv6"
+				uci_set 'network' "${rt_name}_ipv6" 'in' "${iface}"
+				uci_set 'network' "${rt_name}_ipv6" 'lookup' "${ipTablePrefix}_${netifd_interface_default6}"
+				uci_set 'network' "${rt_name}_ipv6" 'priority' "${lan_priority}"
+			fi
+		lan_priority="$((lan_priority + 1))"
+		fi
+		is_supported_interface "$iface" || return 0
+
+		if [ -z "$target_iface" ] || [ "$target_ifance" = "$iface" ]; then
+			is_wan6 "$iface" && return # TODO: properly process wan/wan6 at some point
+			if [ -z "$netifd_strict_enforcement" ] && [ "$netifd_interface_default" = "$iface" ]; then
+				rt_name='main'
+			fi
+			case "$action" in
+				install)
+					output 2 "Setting up netifd extensions for $iface... "
+					[ "$rt_name" = 'main' ] || sed -i "\#${rt_name}\$#d" "$rtTablesFile" >/dev/null 2>&1
+					[ "$rt_name" = 'main' ] || echo "${tid} ${rt_name}" >> "$rtTablesFile"
+					uci_set 'network' "${iface}" 'ip4table' "${rt_name}"
+					uci_set 'network' "${iface}" 'ip6table' "${rt_name}"
+					uci_add 'network' 'rule' "${rt_name}_ipv4"
+					uci_set 'network' "${rt_name}_ipv4" 'priority' "${priority}"
+					uci_set 'network' "${rt_name}_ipv4" 'lookup' "${rt_name}"
+					uci_set 'network' "${rt_name}_ipv4" 'mark' "${mark}"
+					uci_set 'network' "${rt_name}_ipv4" 'mask' "${fw_mask}"
+					if [ -n "$ipv6_enabled" ]; then
+						uci_add 'network' 'rule6' "${rt_name}_ipv6"
+						uci_set 'network' "${rt_name}_ipv6" 'priority' "${priority}"
+						uci_set 'network' "${rt_name}_ipv6" 'lookup' "${rt_name}"
+						uci_set 'network' "${rt_name}_ipv6" 'mark' "${mark}"
+						uci_set 'network' "${rt_name}_ipv6" 'mask' "${fw_mask}"
+					fi
+					sed -i "\#${mark}#d" "$nftTempFile" >/dev/null 2>&1
+					nft add chain inet "$nftTable" "${nftPrefix}_mark_${mark}"
+					nft add rule inet "$nftTable" "${nftPrefix}_mark_${mark} ${nftRuleParams} meta mark set (meta mark & ${fw_maskXor}) | ${mark}"
+					nft add rule inet "$nftTable" "${nftPrefix}_mark_${mark} return"
+					output_okb
+				;;
+				remove|uninstall)
+					output 2 "Removing netifd extensions for $iface... "
+					[ "$rt_name" = 'main' ] || sed -i "\#${rt_name}\$#d" "$rtTablesFile" >/dev/null 2>&1
+					sed -i "\#${mark}#d" "$nftNetifdPermFile" >/dev/null 2>&1
+					uci_remove 'network' "${iface}" 'ip4table' "${rt_name}" 2>/dev/null
+					uci_remove 'network' "${iface}" 'ip6table' "${rt_name}" 2>/dev/null
+					output_okb
+				;;
+			esac
+		fi
+		mark="$(printf '0x%06x' $((mark + uplink_mark)))"
+		priority="$((priority - 1))"
+		tid="$((tid + 1))"
+	}
+
+	load_package_config
+	json 'init'
+
+	local action="${1:-install}"
+	local target_iface="$2"
+	local mark="$(printf '0x%06x' "$uplink_mark")"
+	local priority="$uplink_ip_rules_priority"
+	local lan_priority="$((uplink_ip_rules_priority + 1000))"
+	local tid="$(get_rt_tables_non_pbr_next_id)"
+
+	case "$action" in
+		check)
+			[ "$netifd_enabled" = '1' ]
+			return "$?"
+		;;
+		install)
+			if [ -z "$netifd_strict_enforcement" ]; then
+				json add error 'errorNetifdMissingOption' 'netifd_strict_enforcement'
+				output_error 'errorNetifdMissingOption' 'netifd_strict_enforcement'
+				return 1
+			fi
+			if [ -z "$netifd_interface_default" ]; then
+				json add error 'errorNetifdMissingOption' 'netifd_interface_default'
+				output_error 'errorNetifdMissingOption' 'netifd_interface_default'
+				return 1
+			fi
+			if [ "$(uci_get 'network' "$netifd_interface_default")" != 'interface' ]; then
+				json add error 'errorNetifdInvalidGateway4' "$netifd_interface_default"
+				output_error 'errorNetifdInvalidGateway4' "$netifd_interface_default"
+				return 1
+			fi
+			if [ -n "$netifd_interface_default6" ] && [ "$(uci_get 'network' "$netifd_interface_default6")" != 'interface' ]; then
+				json add error 'errorNetifdInvalidGateway6' "$netifd_interface_default6"
+				output_error 'errorNetifdInvalidGateway6' "$netifd_interface_default6"
+				return 1
+			fi
+			if [ -z "$netifd_interface_local" ]; then
+				json add warning 'warningNetifdMissingInterfaceLocal' 'lan'
+				output_error 'warningNetifdMissingInterfaceLocal' 'lan'
+				netifd_interface_local='lan'
+			fi
+			[ "$netifd_strict_enforcement" = '1' ] || unset netifd_strict_enforcement
+#			[ -n "$netifd_interface_default6" ] || unset ipv6_enabled
+		;;
+		uninstall)
+			unset target_iface
+		;;
+	esac
+
+	nft_file 'netifd_create'
+	output 1 "Netifd extensions $action ${target_iface:+on $target_iface }"
+	config_load 'network'
+	config_foreach _netifd_process_interface 'interface' "$action"
+	output_1_newline
+
+	case "$action" in
+		install)
+			nft_file 'netifd_install'
+			if [ -z "$target_iface" ]; then
+				uci_set "$packageName" 'config' 'netifd_enabled' '1'
+			fi
+		;;
+		remove)
+			if [ -z "$target_iface" ]; then
+				nft_file 'netifd_remove'
+				uci_remove "$packageName" 'config' 'netifd_enabled' 2>/dev/null
+			fi
+		;;
+		uninstall)
+			nft_file 'netifd_remove'
+		;;
+	esac
+	uci_commit "$packageName"
+#	cat "$nftNetifdPermFile"
+#	cat "$rtTablesFile"
+#	uci changes
+#	uci revert network
+	uci_commit 'network'
+	sync
+	output "Restarting network ${action:+(on_$action) }"
+	{ /etc/init.d/network 'reload'; /etc/init.d/firewall 'reload'; } >/dev/null 2>&1 && output_okbn || output_failn
+}
+
 # original idea by @egc112: https://github.com/egc112/OpenWRT-egc-add-on/tree/main/stop-dns-leak
 dns_policy_routing() {
 	local mark i nftInsertOption='add' proto='tcp udp' proto_i
@@ -1121,7 +1308,7 @@ dns_policy_routing() {
 	fi
 
 	if { is_ipv4 "$(str_first_word "$src_addr")" && [ -z "$dest_dns_ipv4" ]; } || \
-		{ is_ipv6 "$(str_first_word "$src_addr")" && [ -z "$dest_dns_ipv6" ]; }; then 
+		{ is_ipv6 "$(str_first_word "$src_addr")" && [ -z "$dest_dns_ipv6" ]; }; then
 		processPolicyError='true'
 		json add error 'errorPolicyProcessMismatchFamily' "${name}: '$src_addr' '$dest_dns':'$dest_dns_port'"
 		return 1
@@ -1244,14 +1431,14 @@ policy_routing() {
 	fi
 
 	# TODO: implement actual family mismatch check on lists
-#	if is_family_mismatch "$src_addr" "$dest_addr"; then 
+#	if is_family_mismatch "$src_addr" "$dest_addr"; then
 #		processPolicyError='true'
 #		json add error 'errorPolicyProcessMismatchFamily' "${name}: '$src_addr' '$dest_addr'"
 #		return 1
 #	fi
 
 	if [ -z "$proto" ]; then
-		if [ -n "${src_port}${dest_port}" ]; then 
+		if [ -n "${src_port}${dest_port}" ]; then
 			proto='tcp udp'
 		else
 			proto='all'
@@ -1307,7 +1494,7 @@ policy_routing() {
 			fi
 		fi
 
-		if [ -n "$dest_addr" ]; then 
+		if [ -n "$dest_addr" ]; then
 			if [ "${dest_addr:0:1}" = "!" ]; then
 				negation='!='; value="${dest_addr//\!}"; nftset_suffix='_neg';
 			else
@@ -1610,18 +1797,33 @@ interface_routing() {
 					ip -6 rule del table "$tid" prio "$priority" >/dev/null 2>&1
 					try ip -6 rule add fwmark "${mark}/${fw_mask}" table "$tid" priority "$priority" || ipv6_error=1
 				fi
-			else
-				if ! grep -q "$tid ${ipTablePrefix}_${iface}" "$rtTablesFile"; then
-					sed -i "/${ipTablePrefix}_${iface}/d" "$rtTablesFile"
-					echo "$tid ${ipTablePrefix}_${iface}" >> "$rtTablesFile"
-					sync
-				fi
-				ip -4 rule flush table "$tid" >/dev/null 2>&1
-				ip -4 route flush table "$tid" >/dev/null 2>&1
-				if [ -n "$gw4" ] || [ -n "$strict_enforcement" ]; then
-					ipv4_error=0
-					if [ -z "$gw4" ]; then
-						try ip -4 route add unreachable default table "$tid" || ipv4_error=1
+				# try ip -4 rule replace fwmark "${mark}/${fw_mask}" lookup 'main' suppress_prefixlength 0 priority "$((priority - 1000))" || ipv4_error=1
+				{
+					for prio in $(ip -4 rule show | awk '/lookup main/ && /suppress_prefixlength 0/ {gsub(":", "", $1); print $1}'); do
+						rule="$(ip -4 rule show | awk -v p="$prio" '($1==p":"){ $1=""; sub(/^ /,""); print }')"
+						[ -n "$rule" ] || continue
+						rule="${rule/lookup main/lookup $tid}"
+						ip -4 rule replace priority "$prio" $rule >/dev/null 2>&1 || ipv4_error=1
+					done
+				}
+				try ip -4 rule replace fwmark "${mark}/${fw_mask}" table "$tid" priority "$priority" || ipv4_error=1
+			fi
+			try nft add chain inet "$nftTable" "${nftPrefix}_mark_${mark}" || ipv4_error=1
+			try nft add rule inet "$nftTable" "${nftPrefix}_mark_${mark} ${nftRuleParams} meta mark set (meta mark & ${fw_maskXor}) | ${mark}" || ipv4_error=1
+			try nft add rule inet "$nftTable" "${nftPrefix}_mark_${mark} return" || ipv4_error=1
+			if [ -n "$ipv6_enabled" ]; then
+				ipv6_error=0
+				if { [ -n "$gw6" ] && [ "$gw6" != "::/0" ]; } || [ -n "$strict_enforcement" ]; then
+					if [ -z "$gw6" ] || [ "$gw6" = "::/0" ]; then
+						try ip -6 route replace unreachable default table "$tid" || ipv6_error=1
+					elif ip -6 route list table main | grep -q " dev $dev6 "; then
+						if ip -6 address show dev "$dev6" | grep -q "BROADCAST"; then
+							try ip -6 route replace default via "$gw6" dev "$dev6" table "$tid" metric "$uplink_interface6_metric" || ipv6_error=1
+						elif ip -6 address show dev "$dev6" | grep -q "POINTOPOINT"; then
+							try ip -6 route replace default dev "$dev6" table "$tid" metric "$uplink_interface6_metric" || ipv6_error=1
+						else
+							json add error 'errorInterfaceRoutingUnknownDevType' "$dev6"
+						fi
 					else
 						try ip -4 route add default via "$gw4" dev "$dev" table "$tid" || ipv4_error=1
 					fi
@@ -1802,7 +2004,7 @@ process_interface() {
 		return 0
 	fi
 
-	if [ "$iface" = 'tor' ]; then 
+	if [ "$iface" = 'tor' ]; then
 		case "$action" in
 			create|reload|reload_interface)
 				torDnsPort="$(get_tor_dns_port)"
@@ -2022,20 +2224,7 @@ boot() {
 	rc_procd start_service 'on_boot' && service_started 'on_boot'
 }
 
-on_firewall_reload() { 
-	if [ ! -e "$packageLockFile" ]; then
-		logger -t "$packageName" "Reload on firewall action aborted: service is stopped."
-		return 0
-	else
-		if nft_file 'exists'; then
-			logger -t "$packageName" "Reusing the fw4 nft file."
-		else
-			rc_procd start_service 'on_firewall_reload' "$1"
-		fi
-	fi
-}
-
-on_interface_reload() { 
+on_interface_reload() {
 	if [ ! -e "$packageLockFile" ]; then
 		logger -t "$packageName" "Reload on interface change aborted: service is stopped."
 		return 0
@@ -2281,7 +2470,7 @@ stop_service() {
 		output_okn
 	else
 		output_failn
-	fi 
+	fi
 	output 1 'Resetting interfaces '
 	config_load 'network'
 	config_foreach process_interface 'interface' 'destroy'
